# Core
title: Millie Macdonald - Blog and assorted sundries
author: Millie Macdonald
email: milliemacdonald4@gmail.com
description: >
  A blog by Millie Macdonald about her adventures in web development.
baseurl: ""
url: "https://metricjs.github.io/"

# Build settings
markdown: kramdown

gems:
  - jekyll-feed
  - jekyll-paginate
exclude:
  - Gemfile
  - Gemfile.lock

paginate: 5
paginate_path: "/page:num/"